
version: 2
updates:
  - package-ecosystem: "npm"  # For Node.js projects using npm
    directory: "/"            # Location of package.json and package-lock.json
    schedule:
      interval: "weekly"      # How often to check for updates
    open-pull-requests-limit: 5  # Limits the number of open pull requests Dependabot will create



