# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Configuration for Dependabot
version: 2
updates:
  # Enable updates for npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/"  # The package.json is in the root directory of the repo
    schedule:
      interval: "weekly"  # Check for updates once a week
    open-pull-requests-limit: 5  # Limits the number of open pull requests to 10
    commit-message:
      prefix: "chore"  # Prefix to denote maintenance changes in commit messages
      include: "scope"  # Include the scope of the dependency in the commit message

