name: 'Deploy demo-app using Terraform to AWS'

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_timestamp.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Generate timestamp-based image tag
        id: set_timestamp
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          DATE=$(date +'%Y%m%d%H%M%S')
          IMAGE_TAG=v${DATE}
          echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "::set-output name=image_tag::${IMAGE_TAG}"

      - name: Build and push Docker image with timestamp tag
        run: |
          docker build . -t ghcr.io/${REPO_OWNER}/ghcr-democicdapp:${IMAGE_TAG}
          docker push ghcr.io/${REPO_OWNER}/ghcr-democicdapp:${IMAGE_TAG}

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@v0.6.0
        with:
          image-ref: 'ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.txt'

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: trivy-scan-results
          path: trivy-report.txt

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: build-and-push
    defaults:
      run:
        working-directory: terraform
    env:
      DOCKER_IMAGE_TAG: ${{ needs.build-and-push.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Format and Write Changes
        run: terraform fmt -recursive

      - name: Terraform Plan
        run: terraform plan -var="docker_image_tag=${{ env.DOCKER_IMAGE_TAG }}" -var="repo_owner=${{ github.repository_owner }}" -lock=false

      - name: Terraform Apply
        run: terraform apply -var="docker_image_tag=${{ env.DOCKER_IMAGE_TAG }}" -var="repo_owner=${{ github.repository_owner }}" -auto-approve -lock=false
