name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}


    - name: Set lowercase repository owner
      id: repo_owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        echo "Image name: ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:${{ github.sha }}"
        docker build . -t ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:${{ github.sha }}

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ env.REPO_OWNER }}/ghcr-democicdapp:${{ github.sha }}
