name: OWASP ZAP Security Scan

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 12 * * *'  # Scheduled to run daily at noon
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest
    name: Run OWASP ZAP Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap2docker-stable:latest  # Ensure you're using the latest stable image

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.1  # Using updated action version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://${{ secrets.EC2_PUBLIC_IP }}'  # Target your EC2 instance
          docker_name: 'owasp/zap2docker-stable:latest'
          rules_file_name: '.zap/rules.tsv'  # Specify your rules file if needed
          cmd_options: '-a'  # Any additional command line options

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: owasp-zap-report.md
