name: OWASP ZAP Security Scan

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 12 * * *' # Scheduled to run daily at noon

jobs:
  owasp-zap-scan:
    name: Run OWASP ZAP Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull OWASP ZAP Docker Image
        run: docker pull owasp/zap2docker-stable:latest

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://${{ secrets.EC2_PUBLIC_IP }}'
          docker_name: 'owasp/zap2docker-stable:latest'
          # Ensure EC2_PUBLIC_IP is set in your GitHub secrets with the value of your EC2 instance's public IP.

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-scan-report
          path: owasp-zap-report.md
