name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    name: Scan the Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner and save the report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ezio22/cicddemoapp:latest'
          format: 'json'  # Changed to 'json' for detailed output; change back to 'table' if preferred
          output: 'trivy-report.json'  # Ensure this matches the format
          exit-code: '1'  # The job will fail if vulnerabilities are found
          ignore-unfixed: true  # Focuses on vulnerabilities with available fixes

      - name: Upload Trivy scan report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-report.json  # Ensure this matches the output file
