name: Trivy Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    name: Scan the Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Assuming you're scanning an image from a registry. Replace 'your-image-name' and 'your-tag' accordingly.
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ezio22/cicddemoapp:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
